In [1]:
import seaborn as sns

<class 'ModuleNotFoundError'>: No module named 'seaborn'

In [2]:
import piplite
await piplite.install('seaborn')


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

<ipython-input-3-b478a6fd18e5>:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [4]:
from pyodide.http import pyfetch

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())

In [5]:
file_path= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/automobileEDA.csv"

await download(file_path, "usedcars.csv")
file_name="usedcars.csv"

In [6]:
df=pd.read_csv("file name")

<class 'FileNotFoundError'>: [Errno 44] No such file or directory: 'file name'

In [7]:
df=pd.read_csv("file_name")

<class 'FileNotFoundError'>: [Errno 44] No such file or directory: 'file_name'

In [8]:
df=pd.read_csv("usedcars.csv")

In [9]:
df=pd.read_csv(file_name)

In [10]:
df.head(5)

symboling  normalized-losses         make aspiration num-of-doors  \
0          3                122  alfa-romero        std          two   
1          3                122  alfa-romero        std          two   
2          1                122  alfa-romero        std          two   
3          2                164         audi        std         four   
4          2                164         audi        std         four   

    body-style drive-wheels engine-location  wheel-base    length  ...  \
0  convertible          rwd           front        88.6  0.811148  ...   
1  convertible          rwd           front        88.6  0.811148  ...   
2    hatchback          rwd           front        94.5  0.822681  ...   
3        sedan          fwd           front        99.8  0.848630  ...   
4        sedan          4wd           front        99.4  0.848630  ...   

   compression-ratio  horsepower  peak-rpm city-mpg highway-mpg    price  \
0                9.0       111.0    5000.0       21          27  13495.0   
1                9.0       111.0    5000.0       21          27  16500.0   
2                9.0       154.0    5000.0       19          26  16500.0   
3               10.0       102.0    5500.0       24          30  13950.0   
4                8.0       115.0    5500.0       18          22  17450.0   

  city-L/100km  horsepower-binned  diesel  gas  
0    11.190476             Medium       0    1  
1    11.190476             Medium       0    1  
2    12.368421             Medium       0    1  
3     9.791667             Medium       0    1  
4    13.055556             Medium       0    1  

[5 rows x 29 columns]

In [11]:
#linear and multiple regression model

from sklearn.linear_model import LinearRegression

In [12]:
#linear regression object

lm=LinearRegression()
lm

LinearRegression()

In [13]:
#highway-mpg predicting price

X=df[['highway-mpg']]
Y=df[['price']]

In [14]:
lm.fit(X,Y)

LinearRegression()

In [15]:
Yhat=lm.predict(X)
Yhat[0:5]

array([[16236.50464347],
       [16236.50464347],
       [17058.23802179],
       [13771.3045085 ],
       [20345.17153508]])

In [16]:
lm.intercept_

array([38423.30585816])

In [17]:
lm.coef_

array([[-821.73337832]])

In [18]:
#regression object

lm1=LinearRegression

In [19]:
#impact of engine size on price

X=df[['engine-size']]
Y=df[['price']]

In [20]:
lm1.fit(X,Y)

<class 'AttributeError'>: 'DataFrame' object has no attribute '_validate_params'

In [21]:
lm1.fit(['X','Y'])

<class 'AttributeError'>: 'list' object has no attribute '_validate_params'

In [22]:
lm1.fit(df[['engine-size']], df[['price']])
lm1

<class 'AttributeError'>: 'DataFrame' object has no attribute '_validate_params'

In [23]:
lm1.fit(X,Y)
lm1

<class 'AttributeError'>: 'DataFrame' object has no attribute '_validate_params'

In [24]:
lm1.fit(df[['engine-size']], df[['price']])
lm1

<class 'AttributeError'>: 'DataFrame' object has no attribute '_validate_params'

In [25]:
lm1.fit(df[['X']], df[['Y']])
lm1

<class 'KeyError'>: "None of [Index(['X'], dtype='object')] are in the [columns]"

In [26]:
df.head(5)


symboling  normalized-losses         make aspiration num-of-doors  \
0          3                122  alfa-romero        std          two   
1          3                122  alfa-romero        std          two   
2          1                122  alfa-romero        std          two   
3          2                164         audi        std         four   
4          2                164         audi        std         four   

    body-style drive-wheels engine-location  wheel-base    length  ...  \
0  convertible          rwd           front        88.6  0.811148  ...   
1  convertible          rwd           front        88.6  0.811148  ...   
2    hatchback          rwd           front        94.5  0.822681  ...   
3        sedan          fwd           front        99.8  0.848630  ...   
4        sedan          4wd           front        99.4  0.848630  ...   

   compression-ratio  horsepower  peak-rpm city-mpg highway-mpg    price  \
0                9.0       111.0    5000.0       21          27  13495.0   
1                9.0       111.0    5000.0       21          27  16500.0   
2                9.0       154.0    5000.0       19          26  16500.0   
3               10.0       102.0    5500.0       24          30  13950.0   
4                8.0       115.0    5500.0       18          22  17450.0   

  city-L/100km  horsepower-binned  diesel  gas  
0    11.190476             Medium       0    1  
1    11.190476             Medium       0    1  
2    12.368421             Medium       0    1  
3     9.791667             Medium       0    1  
4    13.055556             Medium       0    1  

[5 rows x 29 columns]

In [27]:
df.dtype()

<class 'AttributeError'>: 'DataFrame' object has no attribute 'dtype'

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          201 non-null    int64  
 1   normalized-losses  201 non-null    int64  
 2   make               201 non-null    object 
 3   aspiration         201 non-null    object 
 4   num-of-doors       201 non-null    object 
 5   body-style         201 non-null    object 
 6   drive-wheels       201 non-null    object 
 7   engine-location    201 non-null    object 
 8   wheel-base         201 non-null    float64
 9   length             201 non-null    float64
 10  width              201 non-null    float64
 11  height             201 non-null    float64
 12  curb-weight        201 non-null    int64  
 13  engine-type        201 non-null    object 
 14  num-of-cylinders   201 non-null    object 
 15  engine-size        201 non-null    int64  
 16  fuel-system        201 non

In [29]:
lm1.fit(df[['engine-size']], df[['price']])
lm1

<class 'AttributeError'>: 'DataFrame' object has no attribute '_validate_params'

In [30]:
df.head()

symboling  normalized-losses         make aspiration num-of-doors  \
0          3                122  alfa-romero        std          two   
1          3                122  alfa-romero        std          two   
2          1                122  alfa-romero        std          two   
3          2                164         audi        std         four   
4          2                164         audi        std         four   

    body-style drive-wheels engine-location  wheel-base    length  ...  \
0  convertible          rwd           front        88.6  0.811148  ...   
1  convertible          rwd           front        88.6  0.811148  ...   
2    hatchback          rwd           front        94.5  0.822681  ...   
3        sedan          fwd           front        99.8  0.848630  ...   
4        sedan          4wd           front        99.4  0.848630  ...   

   compression-ratio  horsepower  peak-rpm city-mpg highway-mpg    price  \
0                9.0       111.0    5000.0       21          27  13495.0   
1                9.0       111.0    5000.0       21          27  16500.0   
2                9.0       154.0    5000.0       19          26  16500.0   
3               10.0       102.0    5500.0       24          30  13950.0   
4                8.0       115.0    5500.0       18          22  17450.0   

  city-L/100km  horsepower-binned  diesel  gas  
0    11.190476             Medium       0    1  
1    11.190476             Medium       0    1  
2    12.368421             Medium       0    1  
3     9.791667             Medium       0    1  
4    13.055556             Medium       0    1  

[5 rows x 29 columns]

In [31]:
df[['engine-size']].head(5)

engine-size
0          130
1          130
2          152
3          109
4          136

In [32]:
X.head(5)

engine-size
0          130
1          130
2          152
3          109
4          136

In [33]:
Y.head(5)

price
0  13495.0
1  16500.0
2  16500.0
3  13950.0
4  17450.0

In [34]:
lm1.fit(X,Y)

<class 'AttributeError'>: 'DataFrame' object has no attribute '_validate_params'

In [35]:
lm1.fit(X,Y)
lm1

<class 'AttributeError'>: 'DataFrame' object has no attribute '_validate_params'

In [36]:
X1=df[['engine-size']]
Y1=df[['price']]

In [37]:
lm1

sklearn.linear_model._base.LinearRegression

In [38]:
lm


LinearRegression()

In [39]:
lm1=LinearRegression()

In [40]:
lm1

LinearRegression()

In [41]:
lm1.fit(X,Y)

LinearRegression()

In [42]:
#regression

Yhat=lm.predict(X)

<class 'ValueError'>: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- engine-size
Feature names seen at fit time, yet now missing:
- highway-mpg


In [43]:
Yhat.head(5)

<class 'AttributeError'>: 'numpy.ndarray' object has no attribute 'head'

In [44]:
Yhat.head()

<class 'AttributeError'>: 'numpy.ndarray' object has no attribute 'head'

In [45]:
Yhat_1=lm.predict(X)

<class 'ValueError'>: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- engine-size
Feature names seen at fit time, yet now missing:
- highway-mpg


In [46]:
Yhat_1=lm1.predict(X)

In [47]:
lm1.coef_

array([[166.86001569]])

In [48]:
lm1.intercept_

array([-7963.33890628])